version: '3'

services:
  web:
    build: .
    command: ./docker-entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  test:
    build: .
    command: ptw
    tty: true
    volumes:
      - .:/app